Awesome books: with ES6
maths29/Awesome-books-ES6 pull request #1
Opened 2023-06-13 17:25 UTC by maths29

in this project I:
- Create a separate file for each module in the modules directory.
- Import modules into the index.js file.
- Refactor your functions to arrow functions.
- Display the current date below the navigation bar
- using Luxon

2023-06-13 23:31 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️
 
Hi @maths29,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights:

✅ You used Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ The design looks nice 👍🏽

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-13 23:31 UTC, AmaduKamara commented on modules/ENG.js
> +}
- [ ] Kindly use arrow function syntax for all your functions as required. It's standard in ES6 to use arrow function syntax for your functions. Please modify your functions to arrow function syntax 👍🏽

2023-06-13 23:31 UTC, AmaduKamara commented on modules/addAndRemoveBook.js
> +}
- [ ] Kindly use arrow function syntax for all your functions as required. It's standard in ES6 to use arrow function syntax for your functions. Please modify your functions to arrow function syntax 👍🏽

2023-06-13 23:31 UTC, AmaduKamara commented on modules/localStorage.js
> +}
- [ ] Kindly use arrow function syntax for all your functions as required. It's standard in ES6 to use arrow function syntax for your functions. Please modify your functions to arrow function syntax 👍🏽

2023-06-14 07:33 UTC, wayungi approved these changes
Hi @maths29 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ] All requested changes implemented ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 07:50 UTC, merged